### ISSUE TITLE
Questa does not work with ubuntu 24.04 in 32-bit mode

### ISSUE THREAD

**Issue by rosethompson** [openhwgroup/cvw#1038]
Questa does not run out of the box in Ubuntu 24.04 when launch in the default mode.  By default Questa selects the 32-bit executable and produces the following error.

`/opt/mentor/questasim/bin/../linux/vish: error while loading shared libraries: libXext.so.6: cannot open shared object file: No such file or directory`
 
A work around is to force 64-bit mode with

`MTI_VCO_MODE=64 vsim`

**Comment by jordancarlin** [comment]
Looks like we are doing this when lockstep is enabled already. It should probably just be done for all Questa commands.
