### ISSUE TITLE
Remove deprecated Linux scripts

### ISSUE THREAD

**Issue by jordancarlin** [openhwgroup/cvw#1053]
As mentioned in https://github.com/openhwgroup/cvw/pull/1019#issuecomment-2423552575, several of the scripts in the `linux/testvector-generation` directory are no longer supported. At a minimum this includes `genTrace.sh`, but I suspect there are others that are no longer used as well.

**Comment by rosethompson** [comment]
Looks like we only use fixBinMem and that's just to reverse the byte order of the QEMU memory dump.

**Comment by jordancarlin** [comment]
Mostly resolved with #1062. Still the potential to 
> consolidate further by replacing fixBinMem with objcopy and then move genInitMem.sh into the linux directory.

**Comment by davidharrishmc** [comment]
Did this one get resolved?

**Comment by jordancarlin** [comment]
Yes. Fixed with #1062 and #1081
