### ISSUE TITLE
Add Dependabot to keep submodules up to date

### ISSUE THREAD

**Issue by jordancarlin** [openhwgroup/cvw#1128]
We rely on a variety of submodules, and for several of them almost always want to be on the latest version (cvw-arch-verif, riscv-arch-test, etc). Dependabot is a feature built into GitHub that can automatically open PRs when there is a new version of a submodule (or other dependency). It's used by many other projects, including CVA6. 

For simple submodules like cvw-arch-verif, we can probably just merge the PRs it creates as they are. For more complicated ones like riscv-arch-test it will at least alert us that there is a newer version and we can add other changes that are necessary manually.

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

**Comment by davidharrishmc** [comment]
Sounds promising.  Try it out.  If you don't like it, we can always roll back.

**Comment by jordancarlin** [comment]
Done with PR #1129

**Comment by jordancarlin** [comment]
Seems like it opened a bunch of PRs. We should review which ones we want to merge and which submodules should stay pinned to the current version. We can explicitly exclude any submodules we don't want updated in the Dependabot file.

**Comment by jordancarlin** [comment]
Also a good chance to review if we actually still need/want all of these submodules.

**Comment by jordancarlin** [comment]
Done with PR #1129. Will need modifications to avoid updating submodules that we want pinned to specific versions.
