### ISSUE TITLE
CSR SCOUNTEREN powers up with value 0x1

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#142]
Is this correct ?
It seems odd that SCOUNTEREN powers up with 0x1, yet MCOUNTEREN powers up with value 0x0

Is it intentional ?
it does not affect the reading of the cycle register, as the spec says the following

```
The setting of a bit in mcounteren does not affect whether the corresponding bit in scounteren
is writable. However, U-mode may only access a counter if the corresponding bits in scounteren
and mcounteren are both set.
```

**Comment by davidharrishmc** [comment]
PR#149 should fix this one.

**Comment by eroom1966** [comment]
Confirmed this is fixed
