### ISSUE TITLE
Schematic in top-level README incorrectly labels the instruction cache as "$I" instead of "I$"

### ISSUE THREAD

**Issue by magpyed** [openhwgroup/cvw#172]

**Comment by BigSwoll01** [comment]
Any update on this issue? Has it been fixed?

With more information, my partner and I could take this over.

**Comment by ross144** [comment]
Thanks for the reminder. This should be resolved with pr #223 .

**Comment by ross144** [comment]
@magpyed Hi Lim,

The PR is merged now.  If you are happy please close this issue.
