### ISSUE TITLE
Possible bug in Wally Branch Predictor  jalr ra t0 used as long call incorrectly interpreted as return

### ISSUE THREAD

**Issue by ross144** [openhwgroup/cvw#250]
Working with @infinitymdm and @kjprime to develop coverage of fdivsqrt done concurrent with StallM found a possible bug with the branch predictor.  They used a long call encoded as jalr ra t0 which the branch predictor classified as a return rather than a function call.

**Comment by davidharrishmc** [comment]
Nice job team!
