### ISSUE TITLE
Define Zicntr and Zihpm

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#274]
The Zicntr and Ziphm specifications were recently ratified.  Update the config files to use these names.

**Comment by BigSwoll01** [comment]
Hello David 

My Partner Atir and I will tackle this

**Comment by davidharrishmc** [comment]
Zihpm

**Comment by davidharrishmc** [comment]
Need to edit testbench/riscvassertions to make Zicntr depend on Zicsr and Zihpm depend on Zicntr

**Comment by davidharrishmc** [comment]
Addressed with PR #319
