### ISSUE TITLE
Implement CBO in LSU and IFU

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#356]
IEU produces CMOpM, LSUPrefetchM that go to LSU
Also produces IFUPrefetchE that should go to IFU
During prefetch, IEU generates prefetch address on IEUAdrE

@ross144, it's ready for you to implement the CMO operations and prefetch.
Suggest LSUPrefetchM be equivalent to a read (with rd = x0)
IFUPrefetchM only prefetches if the cache is idle to avoid new stalls?

**Comment by davidharrishmc** [comment]
On further thought, prefetch should be ignored because cache line fetches are blocking so it doesn't help.

CMOOpM also needs to go to IFU.

**Comment by ross144** [comment]
I've completed the CBOM and CBOZ extensions.

**Comment by davidharrishmc** [comment]
PR 393, PR 383, PR389.  Done and verified by Ross.
