### ISSUE TITLE
RV32GC does not work with a DTIM in place of D$

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#368]
In config/rv32gc/config.vh, change DCACHE_SUPPORTED to 0 and DTIM_SUPPORTED to 1.

The LSU has a bunch of lint errors on port sizes and regression fails.

**Comment by ross144** [comment]
I fixed the lint errors (pull request coming soon).  Regression fails because we decided a long time ago not to support a DTIM when FLEN is greater than XLEN.  The test assertion fails.  I don't think it's particularly hard to fix it; however, it will require a change to the DTIM.
