### ISSUE TITLE
ecall is reported as retiring, and increments minstret

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#47]
The ecall instruction does not retire, and it should not increment minstret
from the manual

> As ECALL and EBREAK cause synchronous exceptions, they are not considered to retire, and should not increment the minstret CSR.

The attached (gzipped) elf can reproduce the issue

[ref.elf.gz](https://github.com/openhwgroup/cvw/files/10569808/ref.elf.gz)

**Comment by ross144** [comment]
This is a great find and has implications for our textbook.  For reference this is section 3.3.1 of the privileged specification, last paragraph.

**Comment by eroom1966** [comment]
Hi @ross144 
This is actually masking a few issues later in the execution at the moment when running some tests - but I think I can work around this in the short term

**Comment by ross144** [comment]
I'll have a fix pushed in a few minutes.

**Comment by ross144** [comment]
Fixed by PR #48
