### ISSUE TITLE
Missing extractFunctionRadix.sh - Where can i find this script.

### ISSUE THREAD

**Issue by junambi** [openhwgroup/cvw#482]
extractFunctionRadix.sh ../tests/riscof/work/riscv-arch-test/rv64i_m/B/src/sext.b-01.S/ref/ref.elf.objdump
make: extractFunctionRadix.sh: No such file or directory
make: *** [makefile-memfile:38: ../tests/riscof/work/riscv-arch-test/rv64i_m/B/src/sext.b-01.S/ref/ref.elf.objdump.addr] Error 127

**Comment by davidharrishmc** [comment]
It is in $WALLY/bin

Have you sourced the setup.sh file?  That should put it in your path, along with a bunch of other things you’ll need.

**Comment by junambi** [comment]
Got it, closing this issue.

Thank you.
