### ISSUE TITLE
FFLAGS / FCSR being reported on incorrect instruction retirement

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#49]
@ross144 
It appears that the retirement of some floating point instructions, is reporting the FFLAGS and FCDR in the previous instruction retirement

Here is an example, as you can see below the addi instruction retires, but reports changes to fflags and fcsr
These should be reported on the following fcvt.s instruction

I have attached an elf file to reproduce this behavior
[FCVT-S-L-RTZ-01.elf.gz](https://github.com/openhwgroup/cvw/files/10570545/FCVT-S-L-RTZ-01.elf.gz)

```

# [NOTE] testbench.idv_trace2log @ 8981: RET,0,457,80000770,"79460613 addi    x12,x12,1940   ",x12=00000000c1458794,,,CSR001(fflags)=0000000000000001 CSR003(fcsr)=0000000000000001 CSRb00(mcycle)=000000000000037d CSRb02(minstret)=00000000000001c9,
# Info 457: 'refRoot/cpu', 0x0000000080000770(rvtest_code_begin+360): Machine 79460613 addi    x12,x12,1940
# Info   MEMX 0x80000770 0x80000770 2 0613
# Info   MEMX 0x80000772 0x80000772 2 7946
# Info   x12 00000000c1458000 -> 00000000c1458794
# Error (IDV) CSR register value mismatch (HartId:0, PC:0x0000000080000770 rvtest_code_begin+864):
# Info (IDV)  0> CSR 001 (fflags)
# Info (IDV)   . dut:0x0000000000000001 NV:0 DZ:0 OF:0 UF:0 NX:1
# Info (IDV)   . ref:0x0000000000000000 NV:0 DZ:0 OF:0 UF:0 NX:0
# Info (IDV)  1> CSR 003 (fcsr)
# Info (IDV)   . dut:0x0000000000000001 NV:0 DZ:0 OF:0 UF:0 NX:1 FRM:0(RNE)
# Info (IDV)   . ref:0x0000000000000000 NV:0 DZ:0 OF:0 UF:0 NX:0 FRM:0(RNE)
# [ERROR] testbench.idv_trace2api.state_compare @ 8981: MISMATCH
# [NOTE] testbench.idv_trace2log @ 8991: RET,0,458,80000774,"d0261953 fcvt.s.l f18,x12,rtz   ",,f18=ffffffff4f414587,,CSRb00(mcycle)=000000000000037e CSRb02(minstret)=00000000000001ca,
# Info 458: 'refRoot/cpu', 0x0000000080000774(rvtest_code_begin+364): Machine d0261953 fcvt.s.l f18,x12,rtz
# Info   MEMX 0x80000774 0x80000774 2 1953
# Info   MEMX 0x80000776 0x80000776 2 d026
# Info   f18 0000000000000000 -> ffffffff4f414587
# Info   fflags 0000000000000000 -> 0000000000000001 [NV:0 DZ:0 OF:0 UF:0 NX:1]
# Info   fcsr 0000000000000000 -> 0000000000000001 [NV:0 DZ:0 OF:0 UF:0 NX:1 FRM:0(RNE)]
```

**Comment by eroom1966** [comment]
Looking at the set of tests I have mismatching - it seems closely linked to the fcvt.s instruction
I have around 40 tests targeting fcvt.s and they are all failing

**Comment by ross144** [comment]
I believe I have fixed this.
The root cause was not delaying the csr update utill after a pipeline stall.  It was probably a benign bug, but best to fix it. 
Several performance counters also had this problem.  They likely continued to increment during a pipeline stall.

**Comment by eroom1966** [comment]
@ross144 - I see this is still in your own fork, I will pull in your changes and see if this fixes the issue for me

**Comment by MikeOpenHWGroup** [comment]
Which PR was that @ross144?  (You can reference it by number using a hash tag.)

**Comment by ross144** [comment]
Commit 370931c1cd1efa07b7f4963605170899550f658f fixed the bug.
Some how this got merged in with the pull request which solved the instruction page fault bug, pr #54.

**Comment by MikeOpenHWGroup** [comment]
Thanks @ross144!

Over to you @eroom1966.  Please close this PR if you are satisfied with the fix.

**Comment by MikeOpenHWGroup** [comment]
Hi @ross144, I am re-opening this issue.  Our protocol in Issues is that they should be closed by the person who generated them.

Hi @eroom1966, pls confirm that this fix works for you.

**Comment by eroom1966** [comment]
this is now fixed
