### ISSUE TITLE
ImperasDV decodes 04000043 as fmadd.h but there is no such instruction

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#593]
ImperasDV decodes instruction 04000043 as fmadd.h.  This is incorrect because Zfh does not define half-precision fmadd, fmsub, fnmsub, or fnmadd.  (This caught me by surprise too.)  ImperasDV should produce an illegal instruction exception on instructions of these forms.

This is presently causing a mismatch between ImperasDV and cvw because cvw correctly throws the exception in the fpu.S coverage test.

# Error (IDV)   . ref:04000043 fmadd.h f0,f0,f0,f0,rne

**Comment by eroom1966** [comment]
@davidharrishmc - could you please attach the elf file you are running to this issue

**Comment by davidharrishmc** [comment]
Test case attached.

[8.tar.gz](https://github.com/openhwgroup/cvw/files/14039606/8.tar.gz)

**Comment by davidharrishmc** [comment]
Thanks!  My mistake.  I had thought they existed, then a riscv-arch-test developer pointed me to something saying these instructions do not exist.  It must have been an outdated spec that we were considering.
