### ISSUE TITLE
Single Precision FP instruction mismatches

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#65]
Following on from Issues
https://github.com/openhwgroup/cvw/issues/58
https://github.com/openhwgroup/cvw/issues/57
https://github.com/openhwgroup/cvw/issues/56
https://github.com/openhwgroup/cvw/issues/55

I ran ImperasDV in a mode which pushes through all possible issues, following this I believe all of these instructions have a similar issue of treating the inputs as DP not SP registers
```
fsgnjx.s
fclass.s
fsgnjn.s
fsgnj.s
fneg.s
fabs.s
fmv.s
```

**Comment by davidharrishmc** [comment]
Some or all issues may have been fixed with PR #93 
Lee, please confirm fix.

**Comment by davidharrishmc** [comment]
I didn't make explicit changes to fmv, so it's quite likely the unpacker changes that fixed fsgnj didn't fix fmv.  If you share a failure case, that will make it easy to fix.

**Comment by eroom1966** [comment]
OK, here is an example testcase
```
# [NOTE] testbench.idv_trace2log @ 22751: RET,0,797,000099f0,"e0088f53 fmv.x.s x30,f17        ",x30=00000000ffffffff,,,CSRb00(mcycle)=00000000000008de CSRb02(minstret)=000000000000031d,
# Info 797: 'refRoot/cpu', 0x00000000000099f0(sub_3_2+62): User e0088f53 fmv.x.s x30,f17
# Info   MEMX 0x99f0 0x800099f0 2 8f53
# Info   MEMX 0x99f2 0x800099f2 2 e008
# Info   x30 ffffffffc0000000 -> ffffffffffffffff
# Error (IDV) GPR register value mismatch (HartId:0, PC:0x00000000000099f0):
# Info (IDV)  0> GPR x30
# Info (IDV)   . dut:0x00000000ffffffff
# Info (IDV)   . ref:0xffffffffffffffff
```

This should contain everything required 
[ref.tar.gz](https://github.com/openhwgroup/cvw/files/10785435/ref.tar.gz)

**Comment by eroom1966** [comment]
Fron the Spec
Instructions are provided to move bit patterns between the floating-point and integer registers.
FMV.X.W moves the single-precision value in floating-point register rs1 represented in IEEE 754-
2008 encoding to the lower 32 bits of integer register rd. The bits are not modified in the transfer,
and in particular, the payloads of non-canonical NaNs are preserved. **For RV64, the higher 32 bits
of the destination register are filled with copies of the floating-point number’s sign bit.**

**Comment by eroom1966** [comment]
It appears that all of the SP/FP instructions listed here are now working correctly with the exception of
fmv.x.s

**Comment by eroom1966** [comment]
I think all of these are now resolved
