### ISSUE TITLE
Ugh Our latest pull requests broke the FGPA boot

### ISSUE THREAD

**Issue by ross144** [openhwgroup/cvw#653]
The FPGA is kernel panicking.  I'm going to backout the most obvious changes which cause the problem.

**Comment by ross144** [comment]
Also, the critical path increased. :(

**Comment by davidharrishmc** [comment]
I see this is closed.  Did you solve the root cause?

**Comment by ross144** [comment]
I was mistaken. Somehow I had a stale version of the repo. I pulled the latest copy and it does work.  The critical path is worse however.
