### ISSUE TITLE
Failing derived floating-point configurations

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#655]
The following derived floating-point configurations are not yet passing regression-nightly:

vsim -c -do "do wally-batch.do fh_rv64gc arch64zfh"
  hangs on     "rv64i_m/Zfh/src/fcvt.h.l_b25-01.S",

f_rv32gc_arch32f
fh_rv32gc_arch32f
f_rv64gc_arch64f
f_rv64gc_arch64f
all fail on fmul_b6 sim = 0, signature = 3
(Kevin Kim looking for root cause)

rv64gc_arch64zfad: fcvtmod.w.d not yet working (Jordan Carlin troubleshooting)
   fround/froundx not yet implemented (Jessica Liu and Jordan Carlin writing)

**Comment by jordancarlin** [comment]
fcvtmod.w.d fixed with #674. Issue still remains with Sail for b22 test.

**Comment by davidharrishmc** [comment]
vsim -c -do "do wally-batch.do fh_rv64gc arch64zfh" hangs because arch64zfh fcvtmod.h.l test program performs a fsd, which is not supported in fh.  Consider modifying riscv-arch-test so that fcvtmod instructions that don't depend on d don't use it.

**Comment by jordancarlin** [comment]
fcvtmod.w.d Sail issue with b22 tests resolved in riscv/sail-riscv/pull/442.

**Comment by davidharrishmc** [comment]
Notes from Jordan about fmul failures:
https://docs.google.com/document/d/1p7zb4Vvd1LMBLRgEpXjHyp7etCaFaiBVrBZJM8jediE/edit

**Comment by davidharrishmc** [comment]
Invoke with:
vsim -do "do wally.do f_rv32gc arch32f"

**Comment by davidharrishmc** [comment]
Found a solution to the fmul failures.

**Comment by jordancarlin** [comment]
https://github.com/riscv/sail-riscv/pull/442 was merged and Sail should now produce the correct signature.

**Comment by davidharrishmc** [comment]
Whoo!

**Comment by davidharrishmc** [comment]
Closed with PR #794.
