### ISSUE TITLE
Encountering Error in Make While Simulating Core CVW with Questasim

### ISSUE THREAD

**Issue by WaseemEng** [openhwgroup/cvw#732]
![Error during make](https://github.com/openhwgroup/cvw/assets/142871238/38f0237e-3527-40f3-9bb3-4a707af03fe3)

I am simulating the core CVW .After following the steps outlined in the Git repository for setting up the CVW core simulation environment, I executed the source ./setup.sh command to ensure all configurations were appropriately adjusted, including path changes. However, upon running the make command to initiate the build process, I encountered the above error.

**Comment by ross144** [comment]
Can you check that riscof is installed and in the PATH?
which riscof
/home/rose/.local/bin/riscof

If it's in the path can you run make in cvw/sim and report the error message?

**Comment by davidharrishmc** [comment]
riscv-arch-test is out of date for you.  You'll need to pull a corrected version.

cd $WALLY/addins/riscv-arch-test
git pull

**Comment by WaseemEng** [comment]
Thanks, @ross144, @quswarabid, and @davidharrishmc for your help in resolving the issue.
