### ISSUE TITLE
Create Makefile for separate Questa/VCS coverage targets in their respective directories

### ISSUE THREAD

**Issue by ross144** [openhwgroup/cvw#742]
Currently, the Makefile in sim has a specific target for Questa coverage.  We would like to move this into the questa sub directory.  Ideally any simulator specific config, build targets, or scripts should belong in their respective subdirectory.

**Comment by davidharrishmc** [comment]
Sim organization has changed quite a bit since this issue.  sim/Makefile could still use cleanup, but closing this for now.
