### ISSUE TITLE
Wrong Address for "rvtest_entry_point" in "sumtest"

### ISSUE THREAD

**Issue by europe2024** [openhwgroup/cvw#746]
Below is the platform.

     variant of Debian (version 12) on ARM

"rvtest_entry_point" in "sumtest" at

     $WALLY/examples/asm/sumtest

must be at address 0x0000000080000000 so that the output of various tools match the textbook's examples involving "sumtest" in Chapter 3 RISC-V Software Tool Flow.

The files for compiling sumtest put "rvtest_entry_point" at 0x0000000080003000.

A possible solution is to change

     $WALLY/examples/link/link.ld

by replacing the following line

     .text : { *(.text.init) }

with the following line

     .text : { *(.text.init) *(.text) }

**Comment by davidharrishmc** [comment]
Should be fixed with PR#791

**Comment by davidharrishmc** [comment]
@europe2024 if you are satisfied, can you close the issue?

**Comment by europe2024** [comment]
@davidharrishmc Thanks for updating the code.
