### ISSUE TITLE
Use riscv-arch-test tests instead of wally-riscv-arch-test for Zfa

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#783]

**Comment by davidharrishmc** [comment]
@jordancarlin the riscv-arch-test team suggest that we point our riscv-arch-test submodule to the dev branch instead of the main branch.  This will give us the new version with the fma tests, and will prevent a month-long lag time between PRs being approved into the dev branch and the dev branch being periodically merged into main.

Would you like to make that change, and then get the new FMA tests into tests.vh and then be able to finish this issue?

**Comment by jordancarlin** [comment]
Sounds good. I’ll make the change tonight and update PR #808
