### ISSUE TITLE
Zbkb, Zbkx, Zk* need to be able to be instantiated independently of Zb*

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#809]
As far as I can tell in a brief code review, Zbkb requires Zbb to instantiate the zbb module.

Each of these extensions should be independent, and instantiate no more hardware than necessary.

It would be good to create derived configurations with each extension independently (as well as everything in Zkn without B), and then test those configurations in nightly to make sure they work on the relevant tests.

It would also be good to review the code and check that no hardware is generated unnecessarily for any of the configurations, such as all of Zbb when only Zbkb is requested.

**Comment by jordancarlin** [comment]
Looking at this and it's making me wonder if the names for all of the modules make sense right now. For example, the `zbb` module is now instantiated if either Zbb or Zbkb is enabled (though parts of it are disabled in the case of Zbkb). I'm inclined to leave the names as they are for sake of the book, but it might be confusing now that crypto is added.

This is even more true with the Zkn* extensions, which are purely scalar crypto and don't have bitmanip in their names but are controlled by `bmucontrol` and instantiated in `bitmanipalu`.

**Comment by davidharrishmc** [comment]
The bitmanipalu contains the crypto stuff right now.  We could pull it out into a separate cryptoalu and cryptoctrl in the kmu subdirectory.  However, it all goes into the same mux.  I am actively writing sections on this, and the repartitioning would have to happen quickly to make the book schedule.

Eventually zbb should disable the non-Zbkb features when only Zbkb is supported.

If you're hungry to make these changes in the next few days, we can define a scope of work.  Otherwise, let's leave the partitioning as is.

**Comment by davidharrishmc** [comment]
See also PR #810 removing some redundant logic.  Still in draft form because I might find more as I work on the figures.

**Comment by davidharrishmc** [comment]
Closed by PR #827
