### ISSUE TITLE
FPU fails when supervisor mode is not supported

### ISSUE THREAD

**Issue by jordancarlin** [openhwgroup/cvw#840]
When `S_SUPPORTED` is set to 0 and `F_SUPPORTED` is set to 1, the archXXf tests fail and get stuck in a loop of illegal instructions (as seen below)

`Program fetched illegal instruction 0x00000000 from address 0x00000000.  Might be fault with no fault handler.`

Floating point should not be dependent on privilege modes being supported, just Zicsr. None of the current derived configurations test with s/u modes disabled (other than the ones based on simpler configs like rv32imc), which is likely why this has not been discovered.

**Comment by jordancarlin** [comment]
To reproduce, modify the rv32gc or rv64gc config by setting `S_SUPPORTED = 0`. When `S_SUPPORTED` is turned off, `SSTC_SUPPORTED` and `VIRTMEN_SUPPORTED` (along with the additional virtual memory extensions) must also be turned off.

**Comment by davidharrishmc** [comment]
Great find!  Can you create a derived config to test this?  And do you want to search for the root cause and a fix?

**Comment by jordancarlin** [comment]
I'll definitely create a derived config for it. Should probably also do derived configs for a bunch of the other features with privilege modes disabled. I can also look into a root cause/fix. Nothing immediately obvious, but hopefully something will jump out.
