### ISSUE TITLE
Restore verbose mode for ImperasDV

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#871]
We've lost the ability to run ImperasDV in verbose mode now that we transitioned to wsim.

It seems that we used to do it by passing OTHERFLAGS= *** to vsim in wally.do.

Some scripts such as setup.imperas.sh or sim-imperas set these as

OTHERFLAGS="+TRACE2LOG_ENABLE=1 VERBOSE=1"

I wasn't successful trying this on the questa wally.do file

Adding (or uncommenting the line with)
--trace
--tracemode
to imperas.ic gives us the tracing back, but it would be good to be a wsim option.

**Comment by jordancarlin** [comment]
@davidharrishmc With the changes made in #908, I think we can get this working again. Would you prefer a single option that you pass to wsim that enables a specific set of options, a flag that you pass to wsim that lets you specify desired options (in line with something like --args or the new --params), or using the value of the OTHERFLAGS environment variable?

**Comment by davidharrishmc** [comment]
The wsim user shouldn’t have to remember how to type a bunch of stuff, so it should just be a command line flag.

Maybe --lockstep --verbose.  But maybe --lockstepverbose is better because verbose only modifies lockstep and wouldn’t be used on its own.
