### ISSUE TITLE
Need to enable Crypto extensions in ImperasDV imperas.ic

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#872]
Test with

wsim rv64gc sha256sig1-01.S_ref.elf --elf /home/harris/cvw/tests/riscof/work/riscv-arch-test/rv64i_m/K/src/sha256sig1-01.S/ref/ref.elf --lockstep

**Comment by eroom1966** [comment]
Hi David have you tried using the variant rv64gck ?
Also if you take a look at the document here, and search for crypto
Imperas/ImperasLib/source/riscv.ovpworld.org/processor/riscv/1.0/doc/OVP_Model_Specific_Information_riscv_RV64GCK.pdf

**Comment by davidharrishmc** [comment]
Solved with PR #880
