### ISSUE TITLE
Testfloat on VCS failing

### ISSUE THREAD

**Issue by jordancarlin** [openhwgroup/cvw#911]
Testfloat support is added for VCS in #908, but it is not passing right now. There seem to be a few different distinct issues going on with it. 

- The final vector in a test file is being incorrectly read as all 1s. This seems to happen with most of the rne vectors.
```
$ wsim --tb testbench_fp --sim vcs f_ieee_rv32gc add
Error in f32_add_rne.tv
TestNum          0 VectorNum      46464 OpCtrl 6
inputs: ffffffff 3f800000 ffffffff
SrcA: xxxxxxxx
 Res: 7fffffff 00
 Expected: ffffffff 1f
```
- Likely a separate issue, there is an off-by-one error for several test cases. This seems to happen with most of the non rne vectors.
  - Reproduce by commenting out f32_add_rne.tz and then running
```
$ wsim --tb testbench_fp --sim vcs f_ieee_rv32gc add
Running f32_add_rz.tv vectors 

Error in f32_add_rz.tv
TestNum          0 VectorNum          2 OpCtrl 6
inputs: 9ede38f7 3f800000 3e7f7f7f
SrcA: xxxxxxxx
 Res: 3e7f7f7f 01
 Expected: 3e7f7f7e 01
```

It is not totally consistent. The issues occur with add, sub, mul, fma, cvtint, and cmp but not with div, sqrt, or cvtfp.

**Comment by davidharrishmc** [comment]
TestFloat now runs with the RISC-V model rather than IEEE, so drop _ieee from the configs above:

wsim --tb testbench_fp --sim questa f_rv32gc add --sim vcs 
fails
but passes with --sim questsa
and fails with a lint error in Verilator

**Comment by davidharrishmc** [comment]
Defer fixing testbench_fp on tools other than Questa
