### ISSUE TITLE
CVW does not take an exception on write to hpmcounterX

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#913]
The hpmcounters 0xc00 - 0xc9F are defined as URO
When attempting to write these registers this is succeeding, whereas it should take an "illegal instruction exception"

RET,0,172,80001a4a,"c1e3d5f3 csrrwi  x11,hpmcounter30,7",x11=0000000000000000,,,CSRb00(mcycle)=0000000000000354 CSRb02(minstret)=00000000000000ac,

This instruction is retiring rather than taking an exception

**Comment by davidharrishmc** [comment]
See if PR 914 fixes this for you.

**Comment by davidharrishmc** [comment]
Hopefully PR 914 fixed this.  Let me know if you have any problems.

**Comment by eroom1966** [comment]
Fixed Thanks
