### ISSUE TITLE
Q not supported in GCC 14

### ISSUE THREAD

**Issue by jordancarlin** [openhwgroup/cvw#967]
The `wally-toolchain-installation` script pulls the latest version of [riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain), which was recently updated to use GCC 14. This fails to recognize `q` as a valid extension in the `-march` string, which causes it to fail when building several of our tests.

**Comment by djdiaz** [comment]
Would it make sense to lock the commit the script uses at https://github.com/riscv-collab/riscv-gnu-toolchain/commit/b488ddbd6cdc7d2b951f4bccacc324818356bfc3 until the issue with 14 can be resolved? That's the last commit before the update.

**Comment by jordancarlin** [comment]
Yes. That’s what we are planning to do.

**Comment by djdiaz** [comment]
I'm currently stuck on this, so let me know when you make the change, or I can make it when I have a chance.

**Comment by jordancarlin** [comment]
Running a test installation now and will push the change later today

**Comment by jordancarlin** [comment]
Temporarily pinned in #972. This should be investigated further so that we can switch to GCC 14 at some point down the road.

**Comment by jordancarlin** [comment]
@djdiaz You might need to delete your existing installation if you already tried since the script will only install newer versions by default, not older versions.

**Comment by djdiaz** [comment]
Thank you! Will it be enough to simply rebuild and install the RISC-V toolchain, or are there downstream dependencies that also need to be rebuilt?

**Comment by jordancarlin** [comment]
I haven't tried switching to an older gcc version before so not positive, but I think you should be fine to just rebuild the RISC-V toolchain. elf2hex can be finicky and might also need to be rebuilt.
