### ISSUE TITLE
Incorporate riscvdv directed random tests into lockstep regression

### ISSUE THREAD

**Issue by davidharrishmc** [openhwgroup/cvw#974]

**Comment by jordancarlin** [comment]
In that case should we remove riscv-dv from the repo?On Oct 10, 2024, at 7:59 AM, David Harris ***@***.***> wrote:﻿
Decided against this feature because it doesn't specifically improve coverage.

**Comment by davidharrishmc** [comment]
No, let’s leave it in.  It took a while to set up.
