### ISSUE TITLE
$WALLY/bin/wally-tool-chain-install.sh Fails

### ISSUE THREAD

**Issue by eroom1966** [openhwgroup/cvw#988]
Running on Ubuntu 22.04
when attempting to run the script $WALLY/bin/wally-tool-chain-install.sh as a user (not root)
This fails with the following error

######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################Installing Buildroot and Creating Linux testvectors
######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################Buildroot successfully download.
make[1]: *** [support/dependencies/dependencies.mk:27: dependencies] Error 1
make: *** [Makefile:51: Image] Error 2
Error: Buildroot installation failed
Error on line 387 with command [ "${PIPESTATUS[0]}" == 0 ]

**Comment by eroom1966** [comment]
current hash
commit 428e9d0a6d3c2e97b967db029fa3279a5108e85b (HEAD -> main, origin/main, origin/HEAD)

**Comment by eroom1966** [comment]
Update: it appears that error messages do not come the the console/stdout, I looked in the $RISCV/logs directory and saw this message

**Comment by jordancarlin** [comment]
Thanks for reporting this. Any line with the words error or warning should be printed to stdout. I’ll take a look at tweaking the filter to make sure this message makes it through and may add a check at the beginning for this specific path issue.

**Comment by jordancarlin** [comment]
Should avoided in the future by #988. Let us know if the installation still fails after updating your PATH.

**Comment by jordancarlin** [comment]
@eroom1966 Did rerunning the installation with the modified PATH work?

**Comment by davidharrishmc** [comment]
@eroom1966 are you satisfied?  Can we close this?

**Comment by davidharrishmc** [comment]
Closing this issue.  @eroom1966 please reopen if you need anything else.

**Comment by eroom1966** [comment]
Apologies, yes all resolved after a call with @rosethompson
